CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE TABLE "CollectionThemes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" text NOT NULL,
        "IsHoliday" boolean NOT NULL,
        "ImagePath" text NOT NULL,
        CONSTRAINT "PK_CollectionThemes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FullName" text NOT NULL,
        "Login" text NOT NULL,
        "Email" text NOT NULL,
        "Phone" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "Role" integer NOT NULL,
        "Balance" numeric(10,2) NOT NULL,
        "IsBlocked" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE TABLE "ServiceItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CollectionThemeId" integer NOT NULL,
        "Name" character varying(140) NOT NULL,
        "Description" text NOT NULL,
        "Price" numeric(10,2) NOT NULL,
        "DurationMinutes" integer NOT NULL,
        "ImagePath" text NOT NULL,
        "IsHoliday" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastModifiedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ServiceItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ServiceItems_CollectionThemes_CollectionThemeId" FOREIGN KEY ("CollectionThemeId") REFERENCES "CollectionThemes" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE TABLE "Employees" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Specialty" character varying(100) NOT NULL,
        "QualificationLevel" integer NOT NULL,
        "About" character varying(600) NOT NULL,
        "HireDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Employees" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Employees_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE TABLE "TopUpTransactions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Amount" numeric(10,2) NOT NULL,
        "CardMask" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_TopUpTransactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TopUpTransactions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE TABLE "Bookings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "EmployeeId" integer NOT NULL,
        "ServiceItemId" integer NOT NULL,
        "ScheduledAt" timestamp with time zone NOT NULL,
        "QueueNumber" integer NOT NULL,
        "Status" integer NOT NULL,
        "Notes" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Bookings_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Bookings_ServiceItems_ServiceItemId" FOREIGN KEY ("ServiceItemId") REFERENCES "ServiceItems" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Bookings_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE TABLE "QualificationRequests" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EmployeeId" integer NOT NULL,
        "DesiredLevel" integer NOT NULL,
        "Comment" text NOT NULL,
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_QualificationRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QualificationRequests_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE TABLE "ServiceAssignments" (
        "EmployeeId" integer NOT NULL,
        "ServiceItemId" integer NOT NULL,
        "AttachedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ServiceAssignments" PRIMARY KEY ("EmployeeId", "ServiceItemId"),
        CONSTRAINT "FK_ServiceAssignments_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ServiceAssignments_ServiceItems_ServiceItemId" FOREIGN KEY ("ServiceItemId") REFERENCES "ServiceItems" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE TABLE "Reviews" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "BookingId" integer,
        "EmployeeId" integer,
        "ServiceItemId" integer,
        "Rating" integer NOT NULL,
        "Comment" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Reviews_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Reviews_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Reviews_ServiceItems_ServiceItemId" FOREIGN KEY ("ServiceItemId") REFERENCES "ServiceItems" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Reviews_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_CustomerId" ON "Bookings" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_EmployeeId" ON "Bookings" ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_ServiceItemId" ON "Bookings" ("ServiceItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_CollectionThemes_Name" ON "CollectionThemes" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Employees_UserId" ON "Employees" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE INDEX "IX_QualificationRequests_EmployeeId" ON "QualificationRequests" ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE INDEX "IX_Reviews_BookingId" ON "Reviews" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE INDEX "IX_Reviews_CustomerId" ON "Reviews" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE INDEX "IX_Reviews_EmployeeId" ON "Reviews" ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE INDEX "IX_Reviews_ServiceItemId" ON "Reviews" ("ServiceItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE INDEX "IX_ServiceAssignments_ServiceItemId" ON "ServiceAssignments" ("ServiceItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE INDEX "IX_ServiceItems_CollectionThemeId" ON "ServiceItems" ("CollectionThemeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE INDEX "IX_TopUpTransactions_UserId" ON "TopUpTransactions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Login" ON "Users" ("Login");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418153720_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260418153720_InitialCreate', '8.0.4');
    END IF;
END $EF$;
COMMIT;

